//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int stock_id { get; set; }
        public int product_id { get; set; }
        public int warehouse_id { get; set; }
        public int qty { get; set; }
    
        public virtual product Product { get; set; }
        public virtual warehouse Warehouse { get; set; }
    }
}
