//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stockmanagementEntities : DbContext
    {
        public stockmanagementEntities()
            : base("name=stockmanagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<product> product { get; set; }
        public DbSet<stock> stock { get; set; }
        public DbSet<type> type { get; set; }
        public DbSet<warehouse> warehouse { get; set; }
    }
}
