//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class type
    {
        public type()
        {
            this.Warehouse = new HashSet<warehouse>();
        }
    
        public int type_id { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<warehouse> Warehouse { get; set; }
    }
}
