//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public warehouse()
        {
            this.Stock = new HashSet<stock>();
        }
    
        public int warehouse_id { get; set; }
        public string warehouse_name { get; set; }
        public int warehouse_type { get; set; }
    
        public virtual ICollection<stock> Stock { get; set; }
        public virtual type Type { get; set; }
    }
}
